// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ngx-dashboard/ActivityFeed.tsx": () => import("../components/mockups/ngx-dashboard/ActivityFeed.tsx"),
  "./components/mockups/ngx-dashboard/CommandCentre.tsx": () => import("../components/mockups/ngx-dashboard/CommandCentre.tsx"),
  "./components/mockups/ngx-dashboard/WealthOverview.tsx": () => import("../components/mockups/ngx-dashboard/WealthOverview.tsx")
};
